char y,sad,ra,nen;
int hola, mundo;
bool isBig;
double mydbl other;
char if, else;
int hello();
int hello(char);
int hello(char data);
int hello(int value, bool debug);
int x a;
char function(key, value);